name: finite-observation
channels:
  - pytorch
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - bokeh=3.4.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.6.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.6.2
  - dask-core=2024.6.2
  - dask-expr=1.1.5
  - debugpy=1.8.1
  - decorator=5.1.1
  - distributed=2024.6.2
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.15.3
  - fonttools=4.53.0
  - freetype=2.12.1
  - fsspec=2024.6.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h5py=3.11.0
  - hdf5=1.14.3
  - idna=3.7
  - importlib-metadata=7.2.0
  - importlib_metadata=7.2.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.25.0
  - libgoogle-cloud-storage=2.25.0
  - libgrpc=1.62.2
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.24
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libtorch=2.3.1
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nomkl=1.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.3.1
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.3.2
  - scipy=1.13.1
  - setuptools=70.1.0
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.2.0
  - sortedcontainers=2.4.0
  - stack_data=0.6.2
  - sympy=1.12.1
  - tblib=3.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toolz=0.12.1
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.19.2
  - zstd=1.5.6
