name: finite-observation
channels:
  - pytorch
  - conda-forge
dependencies:
  - ipykernel 
  - matplotlib 
  - pandas 
  - tqdm 
  - h5py 
  - scipy 
  - scikit-learn=1.3.2
  - dask 
  - distributed
  - pytorch=2.3.1
  - torchaudio=2.3.1
  - torchvision=0.18.1